version: '3'
volumes:
  data:
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: routrip
      MYSQL_USER: 7days
      MYSQL_PASSWORD: root
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"